#Â Caddy reverse proxy stack for MediaStack
services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mediastack/config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /mediastack/config/caddy/data:/data
      - /mediastack/config/caddy/config:/config
      - /mediastack/config/caddy/index:/srv/index
    networks:
      - mediastack_net

networks:
  mediastack_net:
    driver: bridge
